### ISSUE TITLE
Errors downloading JRE

### ISSUE THREAD

**Issue by OrangeDog** [wiremock/wiremock-npm#1]
Firstly it reports downloading a JRE to `/home/node/.jdeploy`. There is no `node` user on the system and no such directory.

It then throws because there was no stdout from java.

```
[wiremock] Installing/Updating JRE in /home/node/.jdeploy...
[wiremock] Downloading from:  https://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jre-8u131-linux-x64.tar.gz
[wiremock] 
[wiremock] /home/node/.jdeploy/node_modules/node-jre/index.js:105
[wiremock]     .stdout.trim() === 'No smoke!';
[wiremock]            ^
[wiremock] 
[wiremock] TypeError: Cannot read property 'trim' of null
[wiremock]     at exports.smoketest (/home/node/.jdeploy/node_modules/node-jre/index.js:105:12)
[wiremock]     at Request.request.get.on.on.on (/home/node/.jdeploy/node_modules/node-jre/index.js:141:30)
[wiremock]     at Request.emit (events.js:203:15)
[wiremock]     at IncomingMessage.<anonymous> (/home/node/.jdeploy/node_modules/request/request.js:1083:12)
[wiremock]     at Object.onceWrapper (events.js:286:20)
[wiremock]     at IncomingMessage.emit (events.js:203:15)
[wiremock]     at endReadableNT (_stream_readable.js:1129:12)
[wiremock]     at process._tickCallback (internal/process/next_tick.js:63:19)
[wiremock] /bin/sh: java: not found
[wiremock] npm run wiremock --silent exited with code 1
```

**Comment by tomasbjerre** [comment]
Might be solved by https://github.com/shannah/jdeploy/issues/11

**Comment by OrangeDog** [comment]
I switched over to wiremock-standalone, and ensured there was a JRE installed separately.

**Comment by tomasbjerre** [comment]
For now, if `java` is available (JRE is installed)  then this will not happen.

The difference between this and `wiremock-standalone` is that this package contains the `jar`. It is downloaded from NPM repository. And `wiremock-standalone` downloads it from Central. In my current workplace we don't have access to Central, so this solves my problem.

**Comment by tomasbjerre** [comment]
I found the code here:
https://github.com/shannah/jdeploy/blob/master/src/ca/weblite/jdeploy/jdeploy.js#L63

You should probably transfer this issue to https://github.com/shannah/jdeploy

**Comment by tomasbjerre** [comment]
Perhaps worth investigating jlink and just packaging a standalone executable of wiremock: https://www.baeldung.com/jlink

**Comment by tomasbjerre** [comment]
Will switch to my own npm packaging library:
https://github.com/tomasbjerre/npm-java-runner
