### ISSUE TITLE
Wiremock jar not found

### ISSUE THREAD

**Issue by DominikPieper** [wiremock/wiremock-npm#4]
Hey,

I have a strange error. The error itself is:
20.63 npm ERR! code 1
20.63 npm ERR! path /workdir/node_modules/wiremock-standalone
20.63 npm ERR! command failed
20.63 npm ERR! command sh -c node install.js
20.63 npm ERR! Resolving WireMock version from Maven metadata...
20.63 npm ERR!  https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/maven-metadata.xml
20.63 npm ERR! Downloading WireMock standalone from Maven Central...
20.63 npm ERR!  https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/3.0.1/wiremock-jre8-standalone-3.0.1.jar
20.63 npm ERR!  Error: Request failed with status code 404

It seems like the jar file on maven central isn't there. I can see the meta informations but don't the jar itself on: 
https://repo1.maven.org/maven2/com/github/tomakehurst/wiremock-jre8-standalone/3.0.1/

Is there a broken release or something?
Thanks for any help in further

**Comment by tomasbjerre** [comment]
Looks like you are using:
https://www.npmjs.com/package/wiremock-standalone

This repo is:
https://www.npmjs.com/package/wiremock

This package contains the jar, it does not download from Central.

**Comment by DominikPieper** [comment]
Ah damn, sorry. Wrong npm wiremock package
