### ISSUE TITLE
Add the NPM distribution to the WireMock site

### ISSUE THREAD

**Issue by oleg-nenashev** [wiremock/wiremock-npm#5]
### Summary

https://wiremock.org/docs/ lists various distributions of WireMock. It would be great to add the NPM one to the list, and maybe to the Node.js solutions page

### References

- Contributing to the website: https://github.com/wiremock/wiremock.org/blob/main/CONTRIBUTING.md

**Comment by tomasbjerre** [comment]
Just needs an image to be used together with the link on that page.

**Comment by oleg-nenashev** [comment]
Yep. Here is an SVG under the MIT license https://www.svgrepo.com/svg/452077/npm

**Comment by maelstrom0x8** [comment]
Hello @oleg-nenashev. I would like to work on this.

**Comment by oleg-nenashev** [comment]
@maelstrom0x8 go for it, and thanks for the interest
