### ISSUE TITLE
Publish release version 2.35.1 from wiremock

### ISSUE THREAD

**Issue by peterdenham** [wiremock/wiremock-npm#6]
### Proposal

Version 2.35.1 is tagged in the wiremock repo, but not released on npm.

### References

https://github.com/wiremock/wiremock/releases/tag/2.35.1

**Comment by tomasbjerre** [comment]
Can you motivate the value of releasing that version? If it is just nice to have I don't think I will do it.

**Comment by peterdenham** [comment]
Sure! It's a security patch release.

Without it, security scanners e.g. https://github.com/aquasecurity/trivy will flag any use of the 2.35.0 version with the CVE's mentioned in the release notes.

Dependabot which will (typically) automate upgrading patch versions of packages. With this release, a patch version allows users an easy path to upgrade without jumping to a major version.

That's what I got, but of course, it's your call! Thanks!

**Comment by tomasbjerre** [comment]
Ok. I released it now:
https://www.npmjs.com/package/wiremock/v/2.35.1
Open issue again if any problems.

**Comment by peterdenham** [comment]
Cheers, Tomas!
